namespace FortnoxNET.Constants.Search
{
    public enum CustomerInvoiceSearchParameters
    {
        Credit,
        CostCenter,
        Currency,
        CustomerName,
        CustomerNumber,
        DocumentNumber,
        ExternalInvoiceReference1,
        ExternalInvoiceReference2,
        InvoiceType,
        NotCompleted,
        OCR,
        OurReference,
        Project,
        Sent,
        YourOrderNumber,
        YourReference,
        AccountNumberFrom,
        AccountNumberTo,
        ArticleNumber,
        Description,
        LastModified,
        FinancialYear,
        FinancialYearDate,
        FromDate,
        ToDate
    }
}