name: .NET Core

on:
  push:
    branches:
    - master
    - feature/*
    - hotfix/*
    - patch/*
  pull_request:
    branches:
    - master
    - feature/*
    - hotfix/*
    - patch/*

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2
    
    - name: Install dependencies
      run: |
        cd Fortnox.NET
        dotnet restore
    
    - name: Build
      run: |
        cd Fortnox.NET
        dotnet build --configuration Release --no-restore
    
    - name: Test
      run: |
        cd Fortnox.NET.Tests\Fortnox.NET.Tests\bin\Release\netcoreapp2.2
        VSTest.Console.exe Fortnox.NET.Tests.dll /Tests:FortnoxNET.Tests.AbsenceTransactionsTests
